### ISSUE TITLE
[0.2.4] not working

### ISSUE THREAD

**Issue by prokinkd** [stoleruradu/firegrator#1]
Any command is working at all at version `0.2.4`, no output in CLI, I've waited for several minutes. With or without `GOOGLE_APPLICATION_CREDENTIALS` passed. Works fine at `0.2.3`.

```
$ yarn run firegate --help
yarn run v1.22.10
$ /***/node_modules/.bin/firegate --help
^C
```

I was able to reproduce this issue at GitHub actions with following environment: `runs-on: ubuntu-latest`, `node-version: '14'`

**Comment by stoleruradu** [comment]
Hi, thanks for using `firegate` and reporting the issue, please upgrade to `0.2.5` and everything should work

**Comment by prokinkd** [comment]
Version `0.2.5` working. Thank you for bringing this package and quick response!
